version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: latest/Dockerfile
    ports:
      - ${APP_PORT:-82}:80
    volumes:
      - ${APP_PATH:-~/code}:/var/www/html
      - ./app/latest/logs/nginx:/var/log/nginx
      - ./app/latest/.composer:/root/.composer
    depends_on:
      - mysql
      - postgres
      - redis

  app81:
    build:
      context: ./app
      dockerfile: 81/Dockerfile
    ports:
      - ${APP_81_PORT:-81}:80
    volumes:
      - ${APP_PATH:-~/code}:/var/www/html
      - ./app/81/logs/nginx:/var/log/nginx
      - ./app/81/.composer:/root/.composer
    depends_on:
      - mysql
      - postgres
      - redis

  postgres:
    build:
      context: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secret}
      - POSTGRES_DB=${POSTGRES_DB:-laravel}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
    ports:
      - ${MYSQL_PORT:-3306}:3306

  redis:
    build:
      context: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-secret}
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/etc/redis.conf
    ports:
      - ${REDIS_PORT:-6379}:6379

  localstack:
    image: localstack/localstack:2.0
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
    ports:
      - ${LOCALSTACK_PORT_START:-4563}-${LOCALSTACK_PORT_END:-4599}:4563-4599
    volumes:
      - ./localstack/data:/var/lib/localstack
      - ./localstack/docker-entrypoint-initaws.d:/docker-entrypoint-initaws.d
      - /var/run/docker.sock:/var/run/docker.sock

  mailpit:
    image: axllent/mailpit:latest
    environment:
      - MP_DATA_FILE=/var/lib/mailpit/mailpit.db
    ports:
      - ${MAILPIT_PORT:-1025}:1025
      - ${MAILPIT_UI_PORT:-8025}:8025
    volumes:
      - ./mailpit/data:/var/lib/mailpit